
DROP TABLE IF EXISTS USER_PROJECT_CONNECT;



DROP TABLE IF EXISTS USER_ACCESS_ROLE_LINK;



DROP TABLE IF EXISTS USER_ROLE;



DROP TABLE IF EXISTS USER_ACCESS;



CREATE TABLE USER_ACCESS
(
	USER_ID              BIGINT AUTO_INCREMENT COMMENT '',
	USER_LOGIN_ID        VARCHAR(255) NULL COMMENT '',
	USERNAME             VARCHAR(100) NULL COMMENT '',
	PASSWORD             VARCHAR(255) NULL COMMENT '',
	LOGIN_FAILURE_CNT    INT NULL COMMENT '',
	LOCK_YN              VARCHAR(1) NULL COMMENT '',
	EMAIL                VARCHAR(255) NULL COMMENT '',
	ORGANIZATION         VARCHAR(255) NULL COMMENT '',
	JOB_TITLE            VARCHAR(100) NULL COMMENT '',
	ADMIN_CHANGE_YN      VARCHAR(1) NULL COMMENT '',
	DELETE_YN            VARCHAR(1) NULL COMMENT '',
	REGIST_DATETIME      DATETIME NULL COMMENT '',
	MODIFY_DATETIME      DATETIME NULL COMMENT '',
	PRIMARY KEY (USER_ID)
);



CREATE TABLE USER_ACCESS_ROLE_LINK
(
	USER_ID              BIGINT NOT NULL COMMENT '',
	USER_ROLE_ID         BIGINT NOT NULL COMMENT '',
	PRIMARY KEY (USER_ID,USER_ROLE_ID)
);



CREATE INDEX _USER_ACCESS_ROLE_LINK_1 ON USER_ACCESS_ROLE_LINK
(
	USER_ID
);



CREATE INDEX _USER_ACCESS_ROLE_LINK_2 ON USER_ACCESS_ROLE_LINK
(
	USER_ROLE_ID
);



CREATE TABLE USER_PROJECT_CONNECT
(
	USER_PROJECT_CONNECT_ID BIGINT NOT NULL COMMENT '',
	USER_ID              BIGINT NOT NULL COMMENT '',
	PRIMARY KEY (USER_PROJECT_CONNECT_ID,USER_ID)
);



CREATE INDEX _USER_PROJECT_CONNECT_1 ON USER_PROJECT_CONNECT
(
	USER_ID
);



CREATE TABLE USER_ROLE
(
	USER_ROLE_ID         BIGINT NOT NULL COMMENT '',
	USER_ROLE_CODE       VARCHAR(100) NULL COMMENT '',
	USER_ROLE_NAME       VARCHAR(100) NULL COMMENT '',
	DESCRIPTION          VARCHAR(1000) NULL COMMENT '',
	PRIMARY KEY (USER_ROLE_ID)
);


